---
- name: "Print current directory"
  shell: |
    pwd
    ls
- name: "Extract artifact"
  unarchive: 
    src: artifact.tar.gz
    dest: /home/ubuntu/
    remote_src:  no
- name: "Run app"
  become: true
  shell: |
    cd /home/ubuntu
    pwd
    ls
    npm install
    pm2 stop default
    pm2 start npm -- start