---
- name: "Extract artifact"
  debugger: on_failed
  unarchive: 
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/
    remote_src:  no
- name: "Run app"
  debugger: on_failed
  become: true
  shell: |
    cd /home/ubuntu
    pwd
    ls
    npm install
    pm2 stop default
    pm2 start npm -- start